### ISSUE TITLE
Video description is missing

### ISSUE THREAD

**Issue by YaPaY** [turkish-media-addon/trtarsiv#1]
**original description:**
<img width="1245" alt="resim" src="https://user-images.githubusercontent.com/705923/119340043-4099cb00-bc92-11eb-8246-7a3e506f971a.png">

**addon view:**
<img width="710" alt="resim" src="https://user-images.githubusercontent.com/705923/119340600-041a9f00-bc93-11eb-9e1a-f31077b78f8d.png">

**Comment by vzorlu** [comment]
<img width="952" alt="Ekran Resmi 2021-05-26 14 02 04" src="https://user-images.githubusercontent.com/1226325/119649143-f6981d00-be2a-11eb-88a8-a17b65c53d84.png">

Resim ve açıklama eklendi
